### ISSUE TITLE
Unicode on country_ids.name

### ISSUE THREAD

**Issue by foutoucour** [cgstudiomap/cgstudiomap#104]
A traceback is raised when I try to update the form of [CAOZ hf. (plc)](http://cgstudiomap.org/web#id=555&view_type=form&model=res.partner&menu_id=303&action=386)

Seems there is an issue with unicode of the country name.
```
Traceback (most recent call last):
  File "/home/cgstudiomap/project/cgstudiomap/main/parts/odoo/openerp/http.py", line 530, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/cgstudiomap/project/cgstudiomap/main/parts/odoo/openerp/http.py", line 567, in dispatch
    result = self._call_function(**self.params)
  File "/home/cgstudiomap/project/cgstudiomap/main/parts/odoo/openerp/http.py", line 303, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/cgstudiomap/project/cgstudiomap/main/parts/odoo/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/cgstudiomap/project/cgstudiomap/main/parts/odoo/openerp/http.py", line 300, in checked_call
    return self.endpoint(*a, **kw)
  File "/home/cgstudiomap/project/cgstudiomap/main/parts/odoo/openerp/http.py", line 796, in __call__
    return self.method(*args, **kw)
  File "/home/cgstudiomap/project/cgstudiomap/main/parts/odoo/openerp/http.py", line 396, in response_wrap
    response = f(*args, **kw)
  File "/home/cgstudiomap/project/cgstudiomap/main/parts/odoo/addons/web/controllers/main.py", line 936, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/cgstudiomap/project/cgstudiomap/main/parts/odoo/addons/web/controllers/main.py", line 928, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/home/cgstudiomap/project/cgstudiomap/main/parts/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/cgstudiomap/project/cgstudiomap/main/parts/odoo/openerp/api.py", line 363, in old_api
    result = method(recs, *args, **kwargs)
  File "/home/cgstudiomap/project/cgstudiomap/main/local_modules/res_partner_location_validation/models/res_partner.py", line 237, in write
    return super(ResPartner, self).write(self._clean_location_data(vals))
  File "/home/cgstudiomap/project/cgstudiomap/main/parts/odoo/openerp/api.py", line 239, in wrapper
    return new_api(self, *args, **kwargs)
  File "/home/cgstudiomap/project/cgstudiomap/main/local_modules/main_data/models/res_partner.py", line 56, in write
    return super(ResPartner, self).write(self.add_geo_localization_details(vals))
  File "/home/cgstudiomap/project/cgstudiomap/main/parts/odoo/openerp/api.py", line 239, in wrapper
    return new_api(self, *args, **kwargs)
  File "/home/cgstudiomap/project/cgstudiomap/main/local_modules/main_data/models/res_partner.py", line 41, in add_geo_localization_details
    country=self.env['res.country'].browse(vals.get('country_id')).name,
  File "/home/cgstudiomap/project/cgstudiomap/main/parts/odoo/addons/base_geolocalize/models/res_partner.py", line 60, in geo_query_address
    country])))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 11: ordinal not in range(128)
```

**Comment by foutoucour** [comment]
Same bug on [SITRUS form page](http://cgstudiomap.org/web#id=310&view_type=form&model=res.partner&menu_id=303&action=386)

**Comment by foutoucour** [comment]
I dumped the database and restored it locally. It seems the different work done for the milestone fixed the issue
