### ISSUE TITLE
vals['city'] = geocode.city.encode(__codec__) as NoneType

### ISSUE THREAD

**Issue by foutoucour** [cgstudiomap/cgstudiomap#139]
Address:
231 front street, New York, New York, 11201

```
Traceback (most recent call last):
  File "/home/cgstudiomap/project/cgstudiomap/main/parts/odoo/openerp/http.py", line 536, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/cgstudiomap/project/cgstudiomap/main/parts/odoo/openerp/http.py", line 573, in dispatch
    result = self._call_function(**self.params)
  File "/home/cgstudiomap/project/cgstudiomap/main/parts/odoo/openerp/http.py", line 309, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/cgstudiomap/project/cgstudiomap/main/parts/odoo/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/cgstudiomap/project/cgstudiomap/main/parts/odoo/openerp/http.py", line 306, in checked_call
    return self.endpoint(*a, **kw)
  File "/home/cgstudiomap/project/cgstudiomap/main/parts/odoo/openerp/http.py", line 802, in __call__
    return self.method(*args, **kw)
  File "/home/cgstudiomap/project/cgstudiomap/main/parts/odoo/openerp/http.py", line 402, in response_wrap
    response = f(*args, **kw)
  File "/home/cgstudiomap/project/cgstudiomap/main/parts/odoo/addons/web/controllers/main.py", line 937, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/cgstudiomap/project/cgstudiomap/main/parts/odoo/addons/web/controllers/main.py", line 929, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/home/cgstudiomap/project/cgstudiomap/main/parts/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/cgstudiomap/project/cgstudiomap/main/parts/odoo/openerp/api.py", line 363, in old_api
    result = method(recs, *args, **kwargs)
  File "/home/cgstudiomap/project/cgstudiomap/main/local_modules/main_data/models/res_partner.py", line 60, in write
    self.add_geo_localization_details(vals))
  File "/home/cgstudiomap/project/cgstudiomap/main/parts/odoo/openerp/api.py", line 239, in wrapper
    return new_api(self, *args, **kwargs)
  File "/home/cgstudiomap/project/cgstudiomap/main/local_modules/res_partner_industry/models/res_partner.py", line 101, in write
    self._get_industry_details_from_context(vals)
  File "/home/cgstudiomap/project/cgstudiomap/main/parts/odoo/openerp/api.py", line 239, in wrapper
    return new_api(self, *args, **kwargs)
  File "/home/cgstudiomap/project/cgstudiomap/main/parts/odoo/openerp/api.py", line 546, in new_api
    result = method(self._model, cr, uid, self.ids, *args, **kwargs)
  File "/home/cgstudiomap/project/cgstudiomap/main/parts/connector-telephony/base_phone/base_phone.py", line 260, in write
    cr, uid, ids, vals_reformated, context=context)
  File "/home/cgstudiomap/project/cgstudiomap/main/parts/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/cgstudiomap/project/cgstudiomap/main/parts/odoo/openerp/api.py", line 363, in old_api
    result = method(recs, *args, **kwargs)
  File "/home/cgstudiomap/project/cgstudiomap/main/local_modules/res_partner_location_validation/models/res_partner.py", line 246, in write
    return super(ResPartner, self).write(self._clean_location_data(vals))
  File "/home/cgstudiomap/project/cgstudiomap/main/parts/odoo/openerp/api.py", line 239, in wrapper
    return new_api(self, *args, **kwargs)
  File "/home/cgstudiomap/project/cgstudiomap/main/local_modules/res_partner_location_validation/models/res_partner.py", line 199, in _clean_location_data
    vals['city'] = geocode.city.encode(__codec__)
AttributeError: 'NoneType' object has no attribute 'encode'
```

**Comment by foutoucour** [comment]
Bug reproduced in dev
